Avoid looking up old entries in pg_subtrans, and fix check for aborted XIDs.
This is a backport of this commit from master:

commit b8d958654fbd6fedbd24ffe400d6598173ed64ad
Author: Asim R P <apraveen@pivotal.io>
Date:   Mon Apr 30 09:13:00 2018 -0700

    Readers should check abort status of their subxids

    QE readers incorrectly return true for TransactionIdIsCurrentTransactionId()
    when passed with an xid that is an aborted subtransaction of current
    transaction.  The end effect is wrong results because tuples inserted by the
    aborted subtransaction are seen (treated as visible according to MVCC rules) by
    a reader.  Current patch fixes the bug by looking up abort status of an XID
    from pg_clog.  In a QE writer, just like in upstream PostgreSQL, subtransaction
    information is available in CurrentTransactionState (even when subxip cache has
    overflown).  This information is not maintained in shared memory, making it
    unavailable to a reader.  Readers must resort to a longer route to get the same
    information - pg_subtrans and pg_clog.

    The patch does not use TransactionIdDidAbort() to check abort status.  The
    interface is designed to work with all transaction IDs.  It walks up the
    transaction hierarchy to look for an aborted parent if status of the given
    transaction is found to be SUB_COMMITTED.  This is a wasted effort when a QE
    reader wants to test if its own subtransaction has aborted or not.  A new
    interface is introduced to avoid this wasted effort for QE readers.  We choose
    to rely on AbortSubTransaction()'s behavior to mark entire subtree under the
    aborted subtransaction to be aborted in pg_clog.  A SUB_COMMITTED status in
    pg_clog, therefore, allows us to conclude that the subtransaction is not
    aborted without having to walk up the hierarchy, provided, the subtransaction
    is child of our own transaction.

    The test case also needed a fix because the SQL query (insert into select *)
    didn't result in a reader gang being created.  The SQL is changed to a join on
    a non-distribution column so as to achieve reader gang creation.

5X_STABLE had the same bug.

This also fixes a bug where we tried to look up the status of an old XID
in pg_subtrans, and the file containing that XID had already been
recycled. SubTransactionGetTopmostParent() must not be called with an XID
that's older than TransactionXmin. This commit in master correctly added a
comment to point that out. That lead to to an error like this:

ERROR:  could not access status of transaction 1953791  (seg0 slice1 127.0.0.1:40000 pid=3910)
DETAIL:  Could not open file "pg_subtrans/000E": No such file or directory.

This become topical now, because a customer ran into that error.