Use updated pyOpenSSL for travis pipeline (#8404)
Travis has been failing with
> AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

This error is probably depended on the os packages used. However, since python
is the only demonstration of the dependency, be explicit in adding the
dependency there. Demand a version of pyOpenSSL greater or equal than the
current latest one early on in the pip installation chain.