Remove hard-coded limit on LISTEN_BACKLOG for sequence server
With the hard-coded limit of 64, the following error can happen (if
number of connections to sequence server is greater than 64):
```
Error: Could not read() message from seqserver.(error:104). Closing
connection.
```
Error 104 indicates "connection reset by peer". When the limit of the
listen backlog on the server side is reached, the kernel silently drops
the acknowledgements of the new connections, which will result in this
error on the client side.

So, to better deal with the situation, reuse the GUC used for
interconnect listen backlog limit for sequence server. Hard-coded value
64 does not provide user control over the configuration. The actual
limit will be the minimum of the value set by this GUC and the system
setting `net.core.somaxconn`, which is 128 by default.

Co-authored-by: Ashwin Agrawal <aagrawal@pivotal.io>