Revert "Fix bug that planner generates redundant motion for joins on distribution key"
This reverts commit 1697059e6c710c7e9f7ea6cdd59a97515f2ba9f8.

Due to this commit, full join queries with condition on varchar columns
started failing due to the below error. It is expected that there is a
relabelnode on top of varchar columns while looking up the sort
operator, however because of the said commit we removed the relabelnode.

create table foo(a varchar(30), b varchar(30));
postgres=# select X.a from foo X full join (select a from foo group by 1) Y ON X.a = Y.a;
ERROR:  could not find member 1(1043,1043) of opfamily 1994 (createplan.c:4664)
Will reopen the issue #4175 which brought this patch as we need to rethink the solution.