Fixed error escaping single quote format of shell command for web external table
1) Fixes github issue https://github.com/greenplum-db/gpdb/issues/5925:
If environment variable value contains single quote, it will report error:

```
ERROR:  external table env command ended with error. sh: -c: line 0: unexpected EOF while looking for matching `''  (seg0 slice1 172.31.81.199:6000 pid=7192)
DETAIL:
sh: -c: line 1: syntax error: unexpected end of file
```

The external program executed with COPY PROGRAM or EXECUTE-type external
table is passed a bunch of environment variables. They are passed by
adding them to the command line of the program being executed, with
"<var>=<value> && export VAR && ...". However, the quoting in the code
that builds that command line was broken. Fix it, and add a test.

2) It also fixed: a backslash should not be escaped by duplicating the backslash.
Using single quote as shell quote, only need to escape ' to '\'', no need to escape backslash.
Most escaping problem occurs during display the value.

Notes in testcase about backslash escaping:
- Need to add ESCAPE 'OFF' to EXTERNAL WEB TABLE
- Need to add ESCAPE '&' for LIKE predicate
- For shell 'env' output, don't seperate to 2 columns because CI env has funny char
  in variable value. e.g.
    "LS_OPTIONS=-N --color=tty -T 0" and
    "LESSOPEN=||/usr/bin/lesspipe.sh %s"
- echo will behaves differently on different platforms, force to use bash shell with -E option.